# Docker Compose for local testing
version: "3.8"

services:
    bot:
        build: .
        container_name: praccreminder-bot
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./auth.json:/app/auth.json:ro
            - ./reminder.db:/app/reminder.db
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
